# Generated by Django 3.0.5 on 2020-05-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldclim', '0003_auto_20200517_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climate',
            name='date_time',
            field=models.DateField(),
        ),
    ]
